/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class helloas_kt_com_jni_dynamicword_DynamicWord */

#ifndef _Included_helloas_kt_com_jni_dynamicword_DynamicWord
#define _Included_helloas_kt_com_jni_dynamicword_DynamicWord
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     helloas_kt_com_jni_dynamicword_DynamicWord
 * Method:    createWord
 * Signature: (Ljava/lang/String;Ljava/lang/String;JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_helloas_kt_com_jni_1dynamicword_DynamicWord_createWord
  (JNIEnv *, jobject, jstring, jstring, jlong, jlong, jlong);

/*
 * Class:     helloas_kt_com_jni_dynamicword_DynamicWord
 * Method:    nextWordLeaveInterval
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_helloas_kt_com_jni_1dynamicword_DynamicWord_nextWordLeaveInterval
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     helloas_kt_com_jni_dynamicword_DynamicWord
 * Method:    encryptData
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_helloas_kt_com_jni_1dynamicword_DynamicWord_encryptData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     helloas_kt_com_jni_dynamicword_DynamicWord
 * Method:    decryptData
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_helloas_kt_com_jni_1dynamicword_DynamicWord_decryptData
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
